import type { Metadata } from "next";
import HowContent from "@/app/components/HowContent";

const url = "https://zefer.carrillo.app/how";
const siteUrl = "https://zefer.carrillo.app";

export const metadata: Metadata = {
  title: "How Zefer Encrypts Files with AES-256-GCM",
  description:
    "How Zefer encrypts your secrets end-to-end using AES-256-GCM and PBKDF2. 7 steps from input to decryption explained in detail.",
  keywords: [
    "how encryption works",
    "AES-256-GCM explained",
    "PBKDF2 key derivation",
    "end-to-end encryption",
    "zero knowledge architecture",
    "client-side encryption tutorial",
    "how to encrypt files",
    "browser encryption explained",
  ],
  openGraph: {
    url,
    title: "How It Works | Zefer",
    description:
      "Learn how Zefer encrypts your secrets end-to-end using AES-256-GCM and PBKDF2. 7 steps from input to decryption explained.",
  },
  twitter: {
    card: "summary_large_image",
    title: "How It Works | Zefer",
    description:
      "How Zefer encrypts your secrets end-to-end in 7 steps. AES-256-GCM, PBKDF2, zero-knowledge architecture.",
  },
  alternates: { canonical: url },
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
    { "@type": "ListItem", position: 2, name: "How It Works", item: url },
  ],
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "How does Zefer encrypt files?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Zefer uses AES-256-GCM encryption with PBKDF2-SHA256 key derivation (600,000 iterations). Your passphrase is transformed into a 256-bit key using a unique random 32-byte salt. The content, expiration date, and metadata are encrypted as a single piece with a random 12-byte IV. Everything happens in your browser — no data is sent to any server.",
      },
    },
    {
      "@type": "Question",
      name: "What is a .zefer file?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A .zefer file is a password-protected encrypted file generated by Zefer. It contains your encrypted content packaged with the salt and IV needed for decryption. The file is downloaded directly to your device and can be shared through any channel (email, chat, SMS). Without the correct passphrase, the file is completely unreadable.",
      },
    },
    {
      "@type": "Question",
      name: "Is Zefer encryption truly zero-knowledge?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. Zefer is 100% client-side — all encryption and decryption happens exclusively in your browser using the Web Crypto API. No data, passphrases, or keys are ever sent to a server. The expiration date and security metadata live inside the encrypted payload, making them tamper-proof without the correct key.",
      },
    },
    {
      "@type": "Question",
      name: "How do I decrypt a .zefer file?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Upload the .zefer file to Zefer and enter the passphrase. Your browser repeats the key derivation process, decrypts the content, and checks the expiration. If the passphrase is incorrect, decryption fails without revealing any information. If the file has expired, access is denied.",
      },
    },
    {
      "@type": "Question",
      name: "What encryption algorithm does Zefer use?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Zefer uses AES-256-GCM (Advanced Encryption Standard with Galois/Counter Mode) for encryption and PBKDF2-SHA256 for key derivation with configurable iterations (300,000 / 600,000 / 1,000,000). It uses a 32-byte random salt and a 12-byte random initialization vector (IV) per encryption operation.",
      },
    },
  ],
};

export default function HowPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <HowContent />
    </>
  );
}
